### ISSUE TITLE
Is it possible to license this software in APACHE license

### ISSUE THREAD

**Issue by pellucide** [etr/libhttpserver#109]

**Comment by etr** [comment]
Could you please give me some more details on your request?

**Comment by pellucide** [comment]
Currently the [LICENSE](https://github.com/etr/libhttpserver/blob/master/LICENSE) is LGPL v2.1. Is it possible for you to relicense the distribution of libhttpserver with [APACHE license](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by etr** [comment]
Yeah, I agree with apache being less restrictive.

libhttpserver is currently licensed under LGPL v2.1 because its main linked dependency (libmicrohttpd) is released under the same license. Since both are needed in order for libhttpserver to work I decided to license under this license.

If you are able to let me know your specific use case, I can see if I can help you somehow.

Feel free to re-open in case.

**Comment by pellucide** [comment]
As far as I understand.. ASL (apache software license) and LGPL can **_link_** with each other without any compatibility problems.  

For my specific use case.
Currently, the way I use libhttpserver, it produces an executable. To avoid any licensing issues, I would have to make libhttpserver as a library and link the main app with it. I was just trying to avoid that extra work. 

I may as well do it. I will send a pull-request when I am ready with the modifications.

Thanks for your thoughts
