### ISSUE TITLE
Seg Fault if more than one http_response in render function

### ISSUE THREAD

**Issue by lefty** [etr/libhttpserver#111]
```
const http_response
service_resource::hello_world()
{
    return http_response_builder("Hello World!!!", 200).string_response();
}

const http_response
service_resource::render_GET(const http_request &req)
{
    std::cout << "service_resource::render_GET()" << std::endl;

    if (verbose) std::cout << req;

    std::string datapar = req.get_arg("data");
    if(datapar == "hello")
        return hello_world();


    http_response res(http_response_builder("GET response", 200).string_response());

    if (verbose) std::cout << res;

    return res;

}
```

Causes a Seg Fault if not passing "hello" in the data argument.

**Comment by etr** [comment]
Thanks for notifying. The problem was due to a bad implementation of the http_response copy constructor - to be honest related with the complication of using binders/functors inside. When copying the http_response object the binders associated where copied along retaining the reference to the src http_response object (without being moved to used the destination object).

Fixed now re-generating the binders on copy - the fix is in head and in release 0.13.
