### ISSUE TITLE
[BUG] Travic-CI config doesn't build/test for Windows.

### ISSUE THREAD

**Issue by bcsgh** [etr/libhttpserver#186]
### Prerequisites

* [x] Put an X between the brackets on this line if you have checked that your issue isn't already filed: https://github.com/search?l=&q=repo%3Aetr%2Flibhttpserver&type=Issues

### Description

The current runs on travis-ci.org don't run any Windows cases. However the config does mention windows:
https://github.com/etr/libhttpserver/blob/master/.travis.yml

If I had to guess (and I've never configured Travis so it would be just a guess), I'd suspect that this line here shouldn't have the leading `-`: https://github.com/etr/libhttpserver/blob/master/.travis.yml#L159

### Steps to Reproduce

1. create a PR
2. check the CI link

**Expected behavior:** builds/tests for Windows

**Actual behavior:** Nothing for windows.

**Reproduces how often:** 100%

### Versions
master

**Comment by etr** [comment]
This is not a bug, or at least not in the library. As you can see here: https://github.com/etr/libhttpserver/blob/master/.travis.yml#L123 it is an explicit choice not to run those tests on windows. This is due to the clunky installation of mingw and msys that travis currently has.
An alternative (appveyor) is being evaluated to run those on windows too.

For now, through a quite complex work on the travis configuration, we can automatically run builds on windows that are capturing the majority of the problems that have been appearing on that platform over the years.

For now, until travis doesn't fix their windows support (they are working on it), there is nothing to do here.

**Comment by bcsgh** [comment]
So regardless of if the tests are built, they are not run?

As for the rest, I'm not following; Are you saying that the CI:
- "is building on windows" (I'm seeing evidence that it's not.)
- "could be made to build on windows" (Yes please!)
- "is currently too complex to make build on windows" (Oh, okay.)

Or maybe I'm assuming too much; is travis-ci unable to build a test but then not run it?

**Comment by etr** [comment]
Two different discussions.

1) [Known] Even if building the tests, due to the way they have configured the environment, it will not be able to run them (or, at least, without severe assumptions to how the paths are configured on travis machines, that will break every time they make a change on their side). Because of this, till they are out of their beta on windows, this is not a place where I will be willing to invest.
2) Which I just noticed after my comment. For some reason, with no change to the config it stopped building on windows entirely ( this being the last that executed them https://travis-ci.org/etr/libhttpserver/builds/610168646 ).

Re-opening the issue (and likely will have to open one for travis themselves) to sort 2 out.
